### ISSUE TITLE
Not secure enough

### ISSUE THREAD

**Issue by DiegoFleitas** [gitdemocracy/gitdemocracy#20]
Check PR https://github.com/gitdemocracy/gitdemocracy/pull/19

**Comment by NotNite** [comment]
Please don't open meme issues

**Comment by DiegoFleitas** [comment]
My bad, I thought this was a free country

**Comment by NotNite** [comment]
It is, it's just keep your memes to the PRs - issues are serious

**Comment by DiegoFleitas** [comment]
All right just say you hate democracy
