### ISSUE TITLE
META: Make a bot to automate the tasks

### ISSUE THREAD

**Issue by aveao** [gitdemocracy/gitdemocracy#3]
Sadly, [probot](https://probot.github.io/) flow seems to be node-only, though I'll have to look into it more at a future date.

**Comment by NotNite** [comment]
I'm looking through options right now. I think what it needs to automate would be important:

- Automatically lock comments and only have reactions (if that's even possible)
- Automatically react with thumbs up and thumbs down
- A pull request management system that tracks users and publish date (periodically refreshes, closes prs from new accounts & people with more than 3 open, check whitelisted file types & blacklisted files to modify, check if file is being deleted, maybe send a webhook to a discord channel to notify BDFLs?)
- Auto merge if vote is in favor, it doesn't break any rules, and BDFL has accepted it

**Comment by aveao** [comment]
- I kinda like comments existing tbh. A space for people to tell their views about a specific PR is good.
- Automated reacting sounds good. In the future I might have a website where people can vote without revealing their identity.
- Yep, that's what we need the most rn.
- Yeah, sounds good.

**Comment by ThatNerdyPikachu** [comment]
I could make this if nobody else wants to?

How would we handle the "BDFL has accepted it" point?

**Comment by NotNite** [comment]
Reaction on a Discord embed? Writing a bot instead of a webhook then, probably.

**Comment by ThatNerdyPikachu** [comment]
That'd work, yeah.. Hm...

**Comment by aveao** [comment]
> I could make this if nobody else wants to?

Hell yeah, feel free

> How would we handle the "BDFL has accepted it" point?

Meh, that's not as important. Just merge automatically for now.

**Comment by ThatNerdyPikachu** [comment]
https://github.com/gitdemocracy/gdbot

**Comment by NotNite** [comment]
As there's an individual repo now, this should be closed and issues should be opened in that repository.
